set(_CATKIN_CURRENT_PACKAGE "ca_driver")
set(ca_driver_VERSION "1.3.0")
set(ca_driver_MAINTAINER "Jacob Perron <jperron@sfu.ca>")
set(ca_driver_PACKAGE_FORMAT "2")
set(ca_driver_BUILD_DEPENDS "roslint" "ca_msgs" "diagnostic_msgs" "diagnostic_updater" "geometry_msgs" "libcreate" "nav_msgs" "roscpp" "sensor_msgs" "std_msgs" "tf")
set(ca_driver_BUILD_EXPORT_DEPENDS "ca_msgs" "diagnostic_msgs" "diagnostic_updater" "geometry_msgs" "libcreate" "nav_msgs" "roscpp" "sensor_msgs" "std_msgs" "tf")
set(ca_driver_BUILDTOOL_DEPENDS "catkin")
set(ca_driver_BUILDTOOL_EXPORT_DEPENDS )
set(ca_driver_EXEC_DEPENDS "ca_description" "ca_msgs" "diagnostic_msgs" "diagnostic_updater" "geometry_msgs" "libcreate" "nav_msgs" "roscpp" "sensor_msgs" "std_msgs" "tf")
set(ca_driver_RUN_DEPENDS "ca_description" "ca_msgs" "diagnostic_msgs" "diagnostic_updater" "geometry_msgs" "libcreate" "nav_msgs" "roscpp" "sensor_msgs" "std_msgs" "tf")
set(ca_driver_TEST_DEPENDS )
set(ca_driver_DOC_DEPENDS )
set(ca_driver_URL_WEBSITE "http://wiki.ros.org/ca_driver")
set(ca_driver_URL_BUGTRACKER "")
set(ca_driver_URL_REPOSITORY "")
set(ca_driver_DEPRECATED "")