set(_CATKIN_CURRENT_PACKAGE "create_autonomy")
set(create_autonomy_VERSION "1.3.0")
set(create_autonomy_MAINTAINER "Jacob Perron <jperron@sfu.ca>")
set(create_autonomy_PACKAGE_FORMAT "2")
set(create_autonomy_BUILD_DEPENDS )
set(create_autonomy_BUILD_EXPORT_DEPENDS )
set(create_autonomy_BUILDTOOL_DEPENDS "catkin")
set(create_autonomy_BUILDTOOL_EXPORT_DEPENDS )
set(create_autonomy_EXEC_DEPENDS "ca_description" "ca_driver" "ca_msgs" "ca_tools")
set(create_autonomy_RUN_DEPENDS "ca_description" "ca_driver" "ca_msgs" "ca_tools")
set(create_autonomy_TEST_DEPENDS )
set(create_autonomy_DOC_DEPENDS )
set(create_autonomy_URL_WEBSITE "http://wiki.ros.org/create_autonomy")
set(create_autonomy_URL_BUGTRACKER "")
set(create_autonomy_URL_REPOSITORY "http://github.com/AutonomyLab/create_autonomy")
set(create_autonomy_DEPRECATED "")