set(_CATKIN_CURRENT_PACKAGE "ca_msgs")
set(ca_msgs_VERSION "1.3.0")
set(ca_msgs_MAINTAINER "Jacob Perron <jperron@sfu.ca>")
set(ca_msgs_PACKAGE_FORMAT "2")
set(ca_msgs_BUILD_DEPENDS "message_generation" "std_msgs")
set(ca_msgs_BUILD_EXPORT_DEPENDS "std_msgs")
set(ca_msgs_BUILDTOOL_DEPENDS "catkin")
set(ca_msgs_BUILDTOOL_EXPORT_DEPENDS )
set(ca_msgs_EXEC_DEPENDS "message_runtime" "std_msgs")
set(ca_msgs_RUN_DEPENDS "message_runtime" "std_msgs")
set(ca_msgs_TEST_DEPENDS )
set(ca_msgs_DOC_DEPENDS )
set(ca_msgs_URL_WEBSITE "http://wiki.ros.org/ca_msgs")
set(ca_msgs_URL_BUGTRACKER "")
set(ca_msgs_URL_REPOSITORY "")
set(ca_msgs_DEPRECATED "")