set(_CATKIN_CURRENT_PACKAGE "arduino_roomba")
set(arduino_roomba_VERSION "0.0.0")
set(arduino_roomba_MAINTAINER "roomba <roomba@todo.todo>")
set(arduino_roomba_PACKAGE_FORMAT "1")
set(arduino_roomba_BUILD_DEPENDS "roscpp" "rospy" "std_msgs")
set(arduino_roomba_BUILD_EXPORT_DEPENDS "roscpp" "rospy" "std_msgs")
set(arduino_roomba_BUILDTOOL_DEPENDS "catkin")
set(arduino_roomba_BUILDTOOL_EXPORT_DEPENDS )
set(arduino_roomba_EXEC_DEPENDS "roscpp" "rospy" "std_msgs")
set(arduino_roomba_RUN_DEPENDS "roscpp" "rospy" "std_msgs")
set(arduino_roomba_TEST_DEPENDS )
set(arduino_roomba_DOC_DEPENDS )
set(arduino_roomba_URL_WEBSITE "")
set(arduino_roomba_URL_BUGTRACKER "")
set(arduino_roomba_URL_REPOSITORY "")
set(arduino_roomba_DEPRECATED "")